### ISSUE TITLE
Register this Package!

### ISSUE THREAD

**Issue by NHDaly** [NHDaly/ExceptionUnwrapping.jl#2]
@JuilaRegistrator register

**Comment by NHDaly** [comment]
@JuilaRegistrator register()

**Comment by NHDaly** [comment]
@JuilaRegistrator register()

**Comment by NHDaly** [comment]
@JuliaRegistrator register

**Comment by NHDaly** [comment]
Registering v0.1.1:
@JuliaRegistrator register

**Comment by rai-nhdaly** [comment]
@JuilaRegistrator register

**Comment by NHDaly** [comment]
@JuilaRegistrator register

**Comment by NHDaly** [comment]
@JuliaRegistrator register
